# See https://grafana.com/docs/grafana/v7.5/datasources/postgres/ for a
# documentation on this file.

# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: "Postgres Data Source (ds_postgres)"
  - name: "Github Data Source (ds_github)"
  
datasources:
  - name: "Postgres Data Source (ds_postgres)"
    type: postgres
    # <bool> mark as default datasource. Max one per org
    # TODO(kkleine): which one is correct: default or isDefault?
    isDefault: true
    default: true
    url: postgres:5432
    database: postgres
    user: postgres
    password: example
    # <string> custom UID which can be used to reference this datasource in other parts of the configuration, if not specified will be generated automatically
    uid: ds_postgres
    secureJsonData:
      password: example
    jsonData:
      sslmode: "disable"
      timescaledb: true
      postgresVersion: 1200  # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10 (or above)
    version: 1
    # <bool> allow users to edit datasources from the UI.
    editable: false

  - name: "Github Data Source (ds_github)"
    type: grafana-github-datasource
    # <bool> mark as default datasource. Max one per org
    # TODO(kkleine): which one is correct: default or isDefault?
    isDefault: false
    default: false
    # <string> custom UID which can be used to reference this datasource in other parts of the configuration, if not specified will be generated automatically
    uid: ds_github
    version: 1
    # <bool> allow users to edit datasources from the UI.
    editable: true
